# Generated by Django 4.1.2 on 2023-12-30 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^09\\d{9}$", "تلفن باید شبیه 09123456789 باشد !"
                            )
                        ],
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="وضعیت حساب"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="کاربر ادمین"),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="کد سفارش"
                    ),
                ),
                (
                    "publish",
                    models.DateField(auto_now_add=True, verbose_name="زمان ثبت سفارش"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "جاری"), ("2", "تحویل شده"), ("3", "لغو شده")],
                        default="1",
                        max_length=1,
                        verbose_name="وضعیت سفارش",
                    ),
                ),
                (
                    "whats",
                    models.BooleanField(default=False, verbose_name="ارتباط در وانساپ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لیست سفارش",
                "verbose_name_plural": "لیست سفارشات",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField(default=1, verbose_name="تعداد")),
                (
                    "off",
                    models.CharField(blank=True, max_length=2, verbose_name="تخفیف"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="accounts.cart",
                        verbose_name="سبد خرید",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="posts.post",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم های سفارش",
            },
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField(default=1, verbose_name="تعداد")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_items",
                        to="posts.post",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم های سبد خرید",
            },
        ),
    ]
